### PR TITLE
chi-square test for a fresh dice

### PR DESCRIPTION
**Pull request by evd0kim**
Hi.

I've added a simple Python script which uses only NumPy and SciPy packages, and a short explanation about how to change it to check new dice.

### CODE REVIEW

**Comment by SamouraiDev** [comment]
This text should be in a separate document and pointed to from README.md. Pointing to it from "Original notice" in README.md would be ideal.

**Comment by evd0kim** [comment]
That's clear. I will fix.

**Comment by SamouraiDev** [comment]
Thank you.

**Comment by evd0kim** [comment]
@SamouraiDev done.

**Pull request merged**
